LinkLuaModifier("modifier_pummel_party_hub", "modifiers/modifier_pummel_party_hub", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_pummel_party_pedestal", "modifiers/modifier_pummel_party_pedestal", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_pummel_cup", "modifiers/modifier_pummel_cup", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_move_control", "modifiers/modifier_move_control", LUA_MODIFIER_MOTION_BOTH)
LinkLuaModifier("modifier_pummel_party_pre_mini_game", "modifiers/modifier_pummel_party_pre_mini_game", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_warning_light_thinker", "modifiers/modifier_warning_light_thinker", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_flashlight_debuff", "modifiers/modifier_flashlight_debuff", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_ability_cast_range_custom", "modifiers/modifier_ability_cast_range_custom", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_hero_hidden_custom", "modifiers/modifier_hero_hidden_custom", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_magma_block_custom", "modifiers/modifier_magma_block_custom", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_generic_knockback_lua", "modifiers/modifier_generic_knockback_lua", LUA_MODIFIER_MOTION_BOTH )
LinkLuaModifier("modifier_crown_spawn", "modifiers/modifier_crown_spawn", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_crown_spawn_buff", "modifiers/modifier_crown_spawn_buff", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_hot_potato_debuff", "modifiers/modifier_hot_potato_debuff", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_soul_dropped_thinker", "modifiers/modifier_soul_dropped_thinker", LUA_MODIFIER_MOTION_NONE )